# ---------------------- #
# site config            #
# ---------------------- #
name: 叶子
tagline: 闲言碎语
author: Perry Yeh
url: http://blog.yeeh.org/
baseurl:
permalink: /post/:year/:month/:day/:title.html
paginate: 5
paginate_path: page-:num
excerpt_separator: '<!-- more -->'

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
pygments: true
markdown: redcarpet
timezone: Asia/Shanghai

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# disqus                  #
# ---------------------- #
disqus: yeh

# ---------------------- #
# google analytics       #
# ---------------------- #
google_analytics: UA-11027907-1
google_analytics_domain: yeeh.org
