# ---------------------- #
#      Site Configs      #
# ---------------------- #

name: 叶子
tagline: 闲言碎语
url: http://b.yeeh.org
baseurl:
permalink: /post/:year/:month/:day/:title.html
paginate: 6
paginate_path: page-:num
excerpt_separator: '<!-- more -->'

# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: true
auto: true
pygments: true
markdown: redcarpet
timezone: Asia/Shanghai


# ---------------------- #
#      Compile Sass      #
# ---------------------- #

# run `compass help compile` in terminal to find more available options
sass:
no_line_comments: true
sass_dir: _sass
output_style: compressed


# ---------------------- #
#       Deployment       #
# ---------------------- #

deploy:
repository:
branch:


# ---------------------- #
#    Social Networks     #
# ---------------------- #

# weibo:
#   username:
#   uid:
#   appkey:

# disqus:
disqus: yeh

# google_analytics:
google_analytics: UA-11027907-1