# ---------------------- #
# site config            #
# ---------------------- #
name: 叶子
baseurl:
tagline: 闲言碎语
author: Perry Yeh
url: http://blog.yeh.sh
keywords: front-end,javascript,html,css
description: Things to save and remember of life in Shanghai, China.
permalink: /post/:year/:month/:day/:title.html
paginate: 3
paginate_path: page-:num
excerpt_separator: '<!-- more -->'

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
pygments: true
markdown: kramdown
timezone: Asia/Shanghai

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# disqus                  #
# ---------------------- #
disqus: yeh

# ---------------------- #
# google analytics       #
# ---------------------- #
google_analytics: UA-11027907-1
